repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jenkins
    url: https://charts.jenkins.io
  - name: gitea
    url: https://dl.gitea.com/charts/
  - name: harbor
    url: https://helm.goharbor.io
  - name: sonarqube
    url: https://SonarSource.github.io/helm-chart-sonarqube
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: empathyco
    url: https://empathyco.github.io/helm-charts/

releases:
- name: ingress-nginx
  namespace: ingress-nginx
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  version: 4.11.1
  values:
    - values/ingress-nginx/values.yaml

- name: jenkins
  namespace: jenkins
  createNamespace: true
  chart: jenkins/jenkins
  version: 5.5.3
  values:
    - values/jenkins/values.yaml

- name: gitea
  namespace: gitea
  createNamespace: true
  chart: gitea/gitea
  version: 10.4.0
  values:
    - values/gitea/values.yaml
  
- name: harbor
  namespace: harbor
  createNamespace: true
  chart: harbor/harbor
  version: 1.15.0
  values:
    - values/harbor/values.yaml

- name: sonarqube
  namespace: sonarqube
  createNamespace: true
  chart: sonarqube/sonarqube
  version: 10.6.1
  values:
    - values/sonarqube/values.yaml

- name: argocd
  namespace: argocd
  createNamespace: true
  chart: argo/argo-cd
  version: 7.4.3
  values:
    - values/argocd/values.yaml

- name: imagepullsecret-patcher
  namespace: imagepullsecret-patcher
  createNamespace: true
  chart: empathyco/imagepullsecret-patcher
  version: 1.0.0
  values:
    - values/imagepullsecret-patcher/values.yaml
