apiVersion: v1
stringData:
  .dockerconfigjson: |
    {
        "auths": {
            "harbor.localhost.com": {
                        "auth": "YWRtaW46SGFyYm9yMTIzNDU="
                }
        }
     }
kind: Secret
metadata:
  name: harbor-credentials
  namespace: imagepullsecret-patcher
type: kubernetes.io/dockerconfigjson
